#define IDC_EDIT1	100
#define IDC_EDIT2	101
#define IDC_UPDOWN1	102
#define IDC_UPDOWN2	103

#define	IDM_OPEN		100
#define	IDM_CLOSE		101
#define	IDM_EXIT		102

#define	IDM_STRETCH1	200
#define	IDM_STRETCH2	201
#define	IDM_STRETCH3	202
#define	IDM_STRETCH4	203
#define	IDM_ADJUST		204
#define	IDM_MONO		205
#define	IDM_RGB			206
#define	IDM_ASPECT0		207
#define	IDM_ASPECT1		208
#define	IDM_ASPECT2		209
#define	IDM_FILTER		210
#define IDM_SCANLINES	211
#define IDM_SCREEN8		212

#define	IDM_PLAY		300
#define	IDM_PAUSE		301
#define	IDM_STOP		302
#define	IDM_REW			303
#define	IDM_FRD			304
#define	IDM_REPEAT		305

#define	IDM_ABOUT		400

#define	IDM_SPAKER		999

#define	IDTB_BMP	3000

